 Select * from customer

--Q1. What is the total revenue generated by male vs. female customers?
Select gender, sum(purchase_amount) As revenue from customer group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
Select * from customer  where discount_applied ='Yes'  and purchase_amount > (select avg(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?
Select item_purchased, round(avg(review_rating)::numeric,2) As high_avg_rating from customer  group by  item_purchased order by high_avg_rating desc limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, Round(avg(purchase_amount),2) from customer where shipping_type in('Express','Standard') group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
Select subscription_status,count(customer_id) as total_customer, round(avg(purchase_amount),2) As average_purchased, sum(purchase_amount)as total_revenue from customer group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, (round((sum(case when discount_applied ='Yes' then 1 else 0 end)*100)/count(*),2)) As percentage from customer Group by item_purchased order by percentage desc limit 5

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
With CTE as(
Select customer_id,previous_purchases, 
case
  when previous_purchases= 1 then 'New'
  when previous_purchases between 2 and 10 then 'Returning'
  else 'Loyal'
end as customer_segment
from customer)

select customer_segment, count(*) As total_count from CTE group by customer_segment
  
)

--Q8. What are the top 3 most purchased products within each category? 
With CTE as(
select category, item_purchased,count(customer_id) as total_orders, row_number() over(partition by category order by count(customer_id) desc )as rnk
from customer 
group by category, item_purchased
)

Select Category, item_purchased,total_orders, rnk from CTE where rnk<=3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
Select subscription_status, count(customer_id)as repeat_buyers from customer where previous_purchases>5 group by subscription_status

--Q10. What is the revenue contribution of each age group? 
Select age_group, sum(purchase_amount) as total_revenue from customer group by age_group order by total_revenue desc
